### ISSUE TITLE
Mass points spread outwards when player spawns

### ISSUE THREAD

**Issue by thegreenjag1** [Tanksy/Git-LOUD#10]
(This is my first issue, so bear with me. I'll provide as much info as I can think of)

Loud Version: 4.63

Whenever a player selects a spot and the game starts, the mass points around the spawnpoint are moved outwards. I don't know if this bug or a feature, but it breaks some maps that have mass points close to cliffs or beaches, since the mass points are sometimes unreachable/unbuildable.

![image](https://user-images.githubusercontent.com/19756663/87240417-0a878b80-c3df-11ea-8216-51b81b3e64f9.png)

![image](https://user-images.githubusercontent.com/19756663/87240422-183d1100-c3df-11ea-9d0b-634180479720.png)
![Inked20200712001810_1_LI](https://user-images.githubusercontent.com/19756663/87240441-4fabbd80-c3df-11ea-8c8d-c5c991b71a43.jpg)

**Comment by Sprouto** [comment]
By it's very nature - LOUD spreads any mass points within 35 ogrids of a start point out to a minimum of 35.  And it limits the number to 4.   A second group of 4 can appear at about 55 ogrids.
The purpose of this spread is to insure that LOUD can use any start position for his predefined base layout - and - to discourage the kind of 'turtling' behavior that concentrated mass points can bring about.
This function only applies to start locations.

**Comment by Medasian** [comment]
I was the one taking the screenshots last night. Would it break the AI if it were turned off? Like would it be possible to add a button in the game settings to allow disabling it? I absolutely love the LOUD AI, but having the mass extractors moved around and breaking early game economy, depending entirely on which area you choose to spawn in, turns me off from using it. Such as that screenshot of Shards (A vanilla map), out of the 8 spawn locations, 2 of them only get 2 mass extractors at the start because of where the mass points are moved.

**Comment by tshakah** [comment]
Could this be disabled for non-AI starts?

**Comment by Sprouto** [comment]
While it can be - we do it for ALL start locations since the AI can potentially take over any of those positions and turn them into a base - and clumped mass points will block his base plan (one of the drawbacks of having an organized layout).
